services:
  accomodation-service_frontend:
    build: .
    ports:
      - "4200:4200"
    container_name: accomodation-service_frontend_container
    volumes: # Volume binding
      - './:/usr/src/app'
    command: >
      bash -c "npm start"

